version: '3.7'
services:
  next-app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: next-app.
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app